version: "3.9"
services:
  database-sea:
    container_name: database-sea
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sea
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - mysql:/var/lib/mysql
  php-sea:
    container_name: php-sea
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database-sea
  nginx-sea:
    container_name: nginx-sea
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-sea
      - database-sea
volumes:
  mysql: